drop table IF EXISTS books;

create TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
authorId INT NOT NULL,
title VARCHAR(250) NOT NULL,
priceOld VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);

create TABLE authors(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL
);